sektionsmöte lp1 2022
cthit/dokument pull request #83
Opened 2022-11-13 13:45 UTC by Adenholm

2022-11-14 06:18 UTC, x183 commented
Looks fine, but want an approval from @cthit/styrit before merging and updating the [https://docs.chalmers.it/](docs) website

2022-11-14 07:06 UTC, Hoidi requested changes
Sorry om det blev lite många kommentarer. Men de flesta handlare iallafall om samma sak :) Snyggt jobbat 🚀

2022-11-14 07:06 UTC, Hoidi commented on policies/ekonomisk_policy/ekonomisk_policy.tex
> +Profilering som bekostas av sektionen måste kunna skiljas från privat egendom
Samma som den ovan. Bryt inte en mening på två rader

2022-11-14 07:06 UTC, Hoidi commented on policies/ekonomisk_policy/ekonomisk_policy.tex
> +Den totala kostnaden för intern representation inom kommittén får inte överstiga 900 kr/person och mandatperiod.
damn boi big money 🤑

2022-11-14 07:06 UTC, Hoidi commented on policies/ekonomisk_policy/ekonomisk_policy.tex
> +\revisioned{2022--11--13}
Jag brukade använda datumet för sektionsmötet då beslutet togs. Känns som att det är rätt. Men kan såklart ha fel

2022-11-14 07:06 UTC, Hoidi commented on stadga/studienamnd.tex
> +Studienämnden består av ordförande, kassör samt i reglemente fastställt antal
Bryt inte en mening på två rader

2022-11-14 07:07 UTC, Hoidi commented on policies/ekonomisk_policy/ekonomisk_policy.tex
> +Arbetsmat avser mat och dryck som förtärs av arbetande i samband med sektions-
Att ha endasat en mening på en rad gör att git-diffen blir snyggare i framtiden 👍

2022-11-20 11:02 UTC, Adenholm commented on policies/ekonomisk_policy/ekonomisk_policy.tex
> +\revisioned{2022--11--13}
Aa, jo det känns mer rimligt :) fixar det

2022-11-20 11:32 UTC, Adenholm commented on policies/ekonomisk_policy/ekonomisk_policy.tex
> +Arbetsmat avser mat och dryck som förtärs av arbetande i samband med sektions-
Yes, fixar det 👍

2022-12-13 07:25 UTC, merged